# Generated by Django 6.0.2 on 2026-02-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='origination',
        ),
        migrations.AddField(
            model_name='person',
            name='origination_city',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='origination_state',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='person',
            name='destination_city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='seats_available',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='taking_passengers',
            field=models.BooleanField(),
        ),
    ]
