# Generated by Django 5.2.11 on 2026-02-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_remove_person_origination_person_origination_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='car_class',
            field=models.CharField(choices=[('regular', 'Regular'), ('premium', 'Premium')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='vehicle_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
